<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

namespace GPBMetadata\Google\Protobuf;

use \Google\Protobuf\Internal\GPBType;
use \Google\Protobuf\Internal\FileDescriptorProto;

class Plugin
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }

        $pool->addMessage(
            'google.protobuf.compiler.Version',
            \Google\Protobuf\Compiler\Version::class
        )
        ->optional('major', GPBType::INT32, 1)
        ->optional('minor', GPBType::INT32, 2)
        ->optional('patch', GPBType::INT32, 3)
        ->optional('suffix', GPBType::STRING, 4)
        ->finalizeToPool();

        $pool->addMessage(
            'google.protobuf.compiler.CodeGeneratorRequest',
            \Google\Protobuf\Compiler\CodeGeneratorRequest::class
        )
        ->repeated('file_to_generate', GPBType::STRING, 1)
        ->optional('parameter', GPBType::STRING, 2)
        ->repeated(
            'proto_file',
            GPBType::MESSAGE,
            15,
            'google.protobuf.internal.FileDescriptorProto'
        )
        ->optional(
            'compiler_version',
            GPBType::MESSAGE,
            3,
            'google.protobuf.compiler.Version'
        )
        ->finalizeToPool();


        $pool->addMessage(
            'google.protobuf.compiler.CodeGeneratorResponse',
            \Google\Protobuf\Compiler\CodeGeneratorResponse::class
        )
        ->optional('error', GPBType::STRING, 1)
        ->repeated(
            'file',
            GPBType::MESSAGE,
            15,
            'google.protobuf.compiler.CodeGeneratorResponse_File'
        )
        ->finalizeToPool();


        $pool->addMessage(
            'google.protobuf.compiler.CodeGeneratorResponse_File',
            \Google\Protobuf\Compiler\CodeGeneratorResponse_File::class
        )
        ->optional('name', GPBType::STRING, 1)
        ->optional('insertion_point', GPBType::STRING, 2)
        ->optional('content', GPBType::STRING, 15)
        ->finalizeToPool();

        \GPBMetadata\Google\Protobuf\Internal\Descriptor::initOnce();
        static::$is_initialized = true;
    }
}
